version: '3.7'

services:
  frontend:
    image: ldso/frontend
    container_name: frontend
    build:
      context: ./fe
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./fe/src/:/app/fe/src/
      - ./fe/public/:/app/fe/public/
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - app

  backend:
    image: ldso/backend
    container_name: backend
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    build:
      context: ./be
      dockerfile: Dockerfile
    # Check Dockerfile for cap_add explanation
    cap_add:
      - SYS_ADMIN
    tty: true
    ports:
      - 8000:8000
    volumes:
      - ./be/src:/app/be/src
      - ./be/tests:/app/be/tests
    depends_on:
      - db
    networks:
      - app

  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - app


networks:
  app:
    driver: bridge